database:
    username: "test"
    password: "test"
    sysdba: "n"
    host: >
            (DESCRIPTION =
                    (ADDRESS = (PROTOCOL = TCP)
                               (HOST = 127.0.0.1)
                               (PORT = 1521)
                    )
                        (CONNECT_DATA = (SERVER = DEDICATED)
                                        (SERVICE_NAME = helowin)
                    )
            )
